appName = "chat_room"

[mysql]
host = "mysql8"
name = "realtime-chat-go"
password = "root1234"
port = 3306
tablePrefix = ""
user = "kimongi"

[log]
level = "debug"
path = "logs/chat.log"

[staticPath]
filePath = "web/static/file/"

[msgChannelType]
channelType = "gochannel"

kafkaHosts = "kafka:9092"
kafkaTopic = "go-chat-message"