version: '3'
 
services:
    zookeeper:
        image: zookeeper
        ports:
          - 2182:2181

    kafka:
        image: wurstmeister/kafka
        ports:
            - 9092:9092
        environment:
            KAFKA_BROKER_ID: 0
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.12:9092 
            KAFKA_CREATE_TOPICS: "go-chat-message:2:0"   # Kafka is initialized after starting a topic of 2 partitions (partitions) Topic named Go-Chat-MESSAGE
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
        depends_on:
            - zookeeper

    mysql8:
        image: mysql:8.0
        container_name: mysql8
        restart: always
        environment:
            TZ: Africa/Nairobi 
            MYSQL_ROOT_PASSWORD: thepswdforroot
            MYSQL_DATABASE: realtime-chat
            MYSQL_USER: realtime-chat-go
            MYSQL_PASSWORD: thepswdforrealtime-chat-go
        ports:
            - 3306:3306
        command:
            # Modify mysql8.0 default password strategy to the original strategy (MySQL8.0 to change its default strategy will cause the password to be unable to match)
            --default-authentication-plugin=mysql_native_password
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_general_ci
            --explicit_defaults_for_timestamp=true
            --lower_case_table_names=1
    
    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
        links: 
            - realtime-chat-go
            - realtime-chat-go1
        depends_on: 
            - realtime-chat-go
            - realtime-chat-go1

    realtime-chat-go:
        build: ./ # Pointing to the root of your project
        container_name: realtime-chat-go
        restart: always
        ports:
            - 8888:8888
        links: 
            - mysql8
            - kafka
        depends_on: 
            - mysql8
            - kafka

    realtime-chat-go1:
        build: ./ # Pointing to the root of your project
        restart: always
        container_name: realtime-chat-go1
        links: 
            - mysql8
            - kafka
        depends_on: 
            - mysql8
            - kafka
